--CREATE DATABASE marketplace_db;
--CREATE USER 'marketplace_user'@'localhost' IDENTIFIED BY 'strongpassword';
--GRANT ALL PRIVILEGES ON marketplace_db.* TO 'marketplace_user'@'localhost';
--FLUSH PRIVILEGES;
